name: Deploy Full Stack App with PHP Backend on Docker to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Installer Docker
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    # Installer Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Copier les fichiers frontend
    - name: Copy frontend files
      run: |
        mkdir -p ./frontend-deploy
        cp -r ./client/* ./frontend-deploy/  # Changez './frontend/' en le chemin réel de votre frontend

    # Construire le conteneur Docker pour le backend PHP
    - name: Build PHP Backend Docker Image
      run: docker-compose -f ./serveur_php/docker-compose.yml build

    # Login to Azure Container Registry (ACR)
    - name: Login to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: <TON_REGISTRE_ACR>.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Push Docker image to ACR
    - name: Push Docker image to ACR
      run: docker-compose -f ./serveur_php/docker-compose.yml push

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NomDeTonAppAzure' 
        images: 'monregistreperso.azurecr.io/php-backend:latest'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
