name: Deploy Full Stack App with PHP Backend on Docker to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Copier les fichiers frontend
    - name: Copy frontend files
      run: |
        mkdir -p ./frontend-deploy
        cp -r ./client/* ./frontend-deploy/  

    # Construire le conteneur Docker pour le backend PHP
    - name: Build PHP Backend Docker Image
      run: docker-compose -f ./serveur_php/docker-compose.yml build

    # Login to Azure Container Registry (ACR)
    - name: Login to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: <TON_REGISTRE_ACR>.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Push Docker image to ACR
    - name: Push Docker image to ACR
      run: docker-compose -f ./serveur_php/docker-compose.yml push

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NomDeTonAppAzure' 
        images: 'monregistreperso.azurecr.io/php-backend:latest'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
