name: Deploy Full Stack App with PHP Backend on Docker to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Installer les dépendances du frontend
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./client  # Si ton frontend est dans un sous-dossier

    # Construire le frontend
    - name: Build frontend
      run: npm run build
      working-directory: ./client  # Si ton frontend est dans un sous-dossier

    # Construire le conteneur Docker pour le backend PHP
    - name: Build PHP Backend Docker Image
      run: docker-compose -f ./serveur_php/docker-compose.yml build

    # Pousser l'image Docker sur le registre Azure Container Registry (ACR)
    - name: Login to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: telegraphcontainers.azurecr.io  # Remplace par le nom de ton ACR
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Push Docker image to ACR
      run: docker-compose -f ./serveur_php/docker-compose.yml push

    # Déployer sur Azure Web App à partir de l'image Docker dans ACR
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NomDeTonAppAzure'  # Le nom de ta Web App sur Azure
        images: 'telegraphcontainers.azurecr.io/php-backend:latest'  # Remplace par le nom de l'image et le tag
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
